/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: joshopel (https://sketchfab.com/joshopel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-island-atoll-of-the-beast-6e7ce3a8d7b54fe9b89010e06550c310
Title: Fantasy Island atoll of the Beast
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Beast(props) {
  const { nodes, materials } = useGLTF('/models/fantasy_island_atoll_of_the_beast.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[13.508, 0, -338.874]} rotation={[-Math.PI / 2, 0, 0]} scale={1.387}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object009_CoastFoam_0.geometry}
          material={materials.CoastFoam}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object009_Water_0.geometry}
          material={materials.Water}
        />
      </group>
      <group position={[74.72, 102.654, -1.598]} rotation={[-Math.PI / 2, 0, 0.262]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Seabed_UnderOcean_0.geometry}
          material={materials.UnderOcean}
          position={[715.105, 296.24, -102.654]}
        />
      </group>
      <group position={[-109.796, 76.566, 104.241]} rotation={[-1.445, 0.278, 0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box020_Misc_0.geometry}
          material={materials.Misc}
          position={[0, 0, -6.186]}
        />
      </group>
      <group position={[25.096, 0, -33.657]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box021_OuterRing_0.geometry}
          material={materials.OuterRing}
          position={[1306.83, -20.651, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_Island_0.geometry}
        material={materials.Island}
        position={[-43.747, 0, 258.347]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016_Tentacles_0.geometry}
        material={materials.Tentacles}
        position={[478.111, 114.579, -99.803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gengon002_Castle_0.geometry}
        material={materials.Castle}
        position={[12.387, 53.153, 146.732]}
        rotation={[-Math.PI / 2, 0, -1.123]}
        scale={[0.503, 0.503, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box012_Statues_0.geometry}
        material={materials.Statues}
        position={[830.682, -32.724, -303.331]}
        rotation={[-Math.PI / 2, 0, 0.087]}
        scale={0.637}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object012_banner_0.geometry}
        material={materials.banner}
        position={[12.387, 53.153, 146.732]}
        rotation={[-Math.PI / 2, 0, -1.123]}
        scale={[0.503, 0.503, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box022_Shipstuff_0.geometry}
        material={materials.Shipstuff}
        position={[254.99, 13.436, 284.151]}
        rotation={[-2.071, 0.415, 0.367]}
        scale={0.912}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Star001_Ward_0.geometry}
        material={materials.Ward}
        position={[834.317, 134.467, -44.734]}
        rotation={[-Math.PI / 4, Math.PI / 2, 0]}
        scale={0.365}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002_Trees_0.geometry}
        material={materials.Trees}
        position={[159.015, 59.935, 163.954]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/fantasy_island_atoll_of_the_beast.glb')




